### ISSUE TITLE
Change Timestamp on Diagrams Card

### ISSUE THREAD

**Issue by AlexanderG2207** [ls1intum/apollon-ios#8]
The timestamp on the diagram cards should be changed from the actual date and time to something like "Last edited 2 days ago" to give a better overview.

**Comment by andrewkykoo** [comment]
Hi @AlexanderG2207, I would like to work on this issue. 

Just to clarify the requirement, you would like the timestamp as shown in the screenshot below to say "Last Update: Today", correct?

How specific would you like the timestamp to be? If it was updated / edited 2 mins ago, do you still want it to display "today" or "2 mins ago"?

<img width="347" alt="Screenshot 2024-02-09 at 8 59 14 AM" src="https://github.com/ls1intum/apollon-ios/assets/47183818/ceb0d530-9da2-47cc-9631-0ea49cae4fac">

**Comment by AlexanderG2207** [comment]
Hey @andrewkykoo, thank you for looking into this enhancement!

Ideally, I would like it to always display when it was updated and as accurately as possible. Be creative, maybe you can come up with a more logical approach.

Let's check out some examples:
- A new diagram we created 4 minutes ago on the same day, that has never been updated = "Created 4 minutes ago"
- A new diagram we created 10 hours ago on a different day, that has never been updated = "Created yesterday"
- A diagram that was updated 2 hours ago on the same day= "Updated 2 hours ago"
- A diagram that was updated 7 days ago = "Updated 7 days ago"

So essentially, if it was created/updated on a different day, we show how many days ago and if it was created/updated on the same day, we show the hours or minutes.

I hope that makes sense. Let me know if you need more clarification.

**Comment by andrewkykoo** [comment]
> Hey @andrewkykoo, thank you for looking into this enhancement!
> 
> Ideally, I would like it to always display when it was updated and as accurately as possible. Be creative, maybe you can come up with a more logical approach.
> 
> Let's check out some examples:
> 
> * A new diagram we created 4 minutes ago on the same day, that has never been updated = "Created 4 minutes ago"
> * A new diagram we created 10 hours ago on a different day, that has never been updated = "Created yesterday"
> * A diagram that was updated 2 hours ago on the same day= "Updated 2 hours ago"
> * A diagram that was updated 7 days ago = "Updated 7 days ago"
> 
> So essentially, if it was created/updated on a different day, we show how many days ago and if it was created/updated on the same day, we show the hours or minutes.
> 
> I hope that makes sense. Let me know if you need more clarification.

Thanks for the clarification! I will start working on it. Feel free to assign me to the issue.

**Comment by andrewkykoo** [comment]
Hey @AlexanderG2207, I am trying to push the branch that I worked on but I keep getting github authentication error in xcode. Should I try pushing it to the main branch via terminal? Could you address this issue and let me know what steps I need to take? Thanks.

**Comment by AlexanderG2207** [comment]
Hey @andrewkykoo, you should create a fork of this repo and create a branch on the fork where you push all your commits for this issue. Once you are happy with the code, you can create a pull request from the branch on your fork into the main branch of this repo, which will be reviewed. Here is a tutorial by GitHub for contributing with forks ([Link](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project)). Let me know if you have further questions.

**Comment by andrewkykoo** [comment]
Thanks for the reminder! I thought I forked the repo...  😅 Please review the pull request #10  addressing the enhancement.
